# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loop.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'loop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nloop.proto\x12\x04loop\":\n\x05Route\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tnum_loops\x18\x02 \x01(\x03\x12\x12\n\ncollisions\x18\x03 \x01(\x03\x32\x33\n\x0bLoopService\x12$\n\x06\x64oLoop\x12\x0b.loop.Route\x1a\x0b.loop.Route\"\x00\x42\x04H\x01P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001P\001'
  _globals['_ROUTE']._serialized_start=20
  _globals['_ROUTE']._serialized_end=78
  _globals['_LOOPSERVICE']._serialized_start=80
  _globals['_LOOPSERVICE']._serialized_end=131
# @@protoc_insertion_point(module_scope)
