# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import loop_pb2 as loop__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in loop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoopServiceStub(object):
    """example of loop as a grpc C++ service 

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.doLoop = channel.unary_unary(
                '/loop.LoopService/doLoop',
                request_serializer=loop__pb2.Route.SerializeToString,
                response_deserializer=loop__pb2.Route.FromString,
                _registered_method=True)


class LoopServiceServicer(object):
    """example of loop as a grpc C++ service 

    """

    def doLoop(self, request, context):
        """basic grpc call with blocking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'doLoop': grpc.unary_unary_rpc_method_handler(
                    servicer.doLoop,
                    request_deserializer=loop__pb2.Route.FromString,
                    response_serializer=loop__pb2.Route.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.LoopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.LoopService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoopService(object):
    """example of loop as a grpc C++ service 

    """

    @staticmethod
    def doLoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.LoopService/doLoop',
            loop__pb2.Route.SerializeToString,
            loop__pb2.Route.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
